#!/bin/bash

if [ ${#ONTRAVIS} -gt 0 ] ; then

    cat <<EOF > ~/.cdsapirc
url: https://cds.climate.copernicus.eu/api/v2
key: ${CDSAPIUSER}:${CDSAPIKEY}
EOF

    cat <<EOF > ~/.ecmwfapirc
{
    "url"   : "https://api.ecmwf.int/v1",
    "key"   : "${ECMWFAPIKEY}",
    "email" : "${ECMWFAPIEMAIL}"
}
EOF

    echo "========================================="
    cat ~/.cdsapirc
    echo "========================================="
    cat ~/.ecmwfapirc
    echo "========================================="

else

    echo "========================================="
    echo "Not on travis.ci, do not create api files."
    echo "========================================="

fi


